#Adapted code from chatgpt to set up https using lets encrypt and certbot (see credits)

services:
  nginx:
    image: nginx:latest
    container_name: securaid-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443" # Expose HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt # For Let's Encrypt certificates
      - ./certbot/www:/var/www/certbot # For certificate challenge
    depends_on:
      - backend
      - frontend

  backend:
    image: securaid-backend
    container_name: securaid-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production

  frontend:
    image: securaid-frontend
    container_name: securaid-frontend
    restart: always
    ports:
      - "3000:3000"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done"
